/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'token.index': [];
        'token.create': [];
        'token.store': [];
        'token.destroy': [
            {
                name: 'token';
                required: true;
            },
        ];
        'auth.login': [];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
