# Action name
name: Tests

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
  push:
    branches:
      - master
      - ci-test

# Jobs section
jobs:
  test:
    runs-on: self-hosted
    container:
      image: php:8.4-cli-bookworm
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4

      - name: setup php
        run: "apt update && apt -y install curl libzip-dev libxml2-dev bash \
              && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \
              && docker-php-ext-install soap zip"

      - name: setup npm
        run: "curl -sL https://deb.nodesource.com/setup_24.x | bash - \
        && apt-get install nodejs -y"

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Typescript Types
        run: typescript:transform

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Lint using pint
        run: "./vendor/bin/pint -q -n --test"

      - name: Test with Larastan
        run: "./vendor/bin/pint -q -n --test"

      - name: Typescript Typecheck
        run: "./vendor/bin/pint -q -n --test"

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/phpunit --log-junit test-results/results.xml

#      - name: Publish Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          files: |
#            test-results/**/*.xml
